# Generated by Django 4.0.5 on 2023-07-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catalogo', 'Puede visualizar el catálogo de vehículos'),)},
        ),
    ]
