# Generated by Django 4.0.5 on 2023-08-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='año',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Toyota', 'Toyota'), ('Mercedes Benz', 'Mercedes Benz'), ('BMW', 'BMW'), ('MG Motors', 'MG Motors'), ('Changan', 'Changan'), ('Audi', 'Audi'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('Suzuki', 'Suzuki'), ('Kia', 'Kia'), ('Mazda', 'Mazda'), ('Mitsubishi', 'Mitsubishi')], default='Ford', max_length=20),
        ),
    ]
