# Generated by Django 4.0.5 on 2023-08-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_alter_vehiculo_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Toyota', 'Toyota'), ('Mercedes Benz', 'Mercedes Benz'), ('BMW', 'BMW'), ('MG Motors', 'MG Motors'), ('Changan', 'Changan'), ('Audi', 'Audi'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('Suzuki', 'Suzuki'), ('Kia', 'Kia'), ('Mazda', 'Mazda'), ('Mitsubishi', 'Mitsubishi'), ('Alfa Romeo', 'Alfa Romeo'), ('Volkswagen', 'Volkswagen'), ('Peugeot', 'Peugeot')], default='Ford', max_length=20),
        ),
    ]
